services:
  proposta-app:
    image: pqnojedocker/analisecredito
    environment:
      spring.profiles.active: prod
    depends_on:
      rabbit-mq:
        condition: service_healthy
  rabbit-mq:
    image: rabbitmq:3-management
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      timeout: 5s
      interval: 5s
      retries: 3
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: propostadb