services:
  proposta-app:
    image: pqnojedocker/proposta-app
    environment:
      spring.profiles.active: prod
    depends_on:
      rabbit-mq:
        condition: service_healthy
    ports:
      - "8080:8080"
  rabbit-mq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      timeout: 5s
      interval: 5s
      retries: 3
    networks:
      service_tier:
        aliases:
          - remoterabbitmq
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: propostadb
networks:
  service_tier:
    name: service_tier